export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_DASHBOARD = "SET_USER_DASHBOARD";
export const SET_USER_ROUTINES = "SET_USER_ROUTINES";
export const SET_USER_PROJECTS = "SET_USER_PROJECTS";
export const SET_USER_USEFULSITES = "SET_USER_USEFULSITES";
export const SET_USER_MEMOS = "SET_USER_MEMOS";
